baseURL: "https://v-shenoy.github.io/"
title: Vighnesh Shenoy
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Vighnesh Shenoy
  description: "An outlet for my thoughts."
  keywords: ["Blog", "Personal Website", "Development", "Hugo",  "PaperMod", "Programming", "Computer Science"]
  author: Vighnesh Shenoy
  DateFormat: "Jan 2, 2006"
  defaultTheme: dark
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: true
  showtoc: false
  tocopen: false

  assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
    disableHLJS: false
    disableFingerPrinting: false
    
  label:
    text: "/home/v-shenoy/"

  profileMode:
    enabled: true
    title: "Vighnesh Shenoy"
    subtitle: "I am a software engineer at Microsoft working in the Azure Functions team. Welcome to the dumping ground for my thoughts."
    imageUrl: "/DP-Rock.jpg"
    imageTitle: "a-picture-of-my-face" 
    imageWidth: 375
    imageHeight: 375
    buttons:
      - name: Posts
        url: "/posts/"
      - name: Tags
        url: "/tags/"

  socialIcons:
    - name: github
      url: "https://github.com/v-shenoy"
    - name: linkedin
      url: "https://www.linkedin.com/in/v-shenoy"
    - name: cv
      url: "/resume/"
    - name: email
      url: "mailto:vighneshq@gmail.com"
    - name: twitter
      url: "https://twitter.com/bitsinadatabase"
    - name: lichess
      url: "https://lichess.org/@/bitsinadatabase"
    - name: rss
      url: "/index.xml"

  editPost:
    URL: "https://github.com/v-shenoy/v-shenoy.github.io/content"
    Text: "Suggest changes."
    appendFilePath: true

menu:
  main:
    - identifier: resume
      name: resume
      url: /resume/
      weight: 1
    - identifier: posts
      name: posts
      url: /posts/
      weight: 2
    - identifier: archive
      name: archive
      url: /archive/
      weight: 3
    - identifier: tags
      name: tags
      url: /tags/
      weight: 4
    - identifier: search
      name: search
      url: /search
      weight: 5
    - identifier: rss
      name: rss
      url: /index.xml

outputs:
  home:
    - HTML
    - RSS
    - JSON
