baseURL: "https://v-shenoy.github.io/"
title: Blog — Vighnesh Shenoy
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Blog — Vighnesh Shenoy
  description: "An outlet for my thoughts."
  keywords: ["Blog", "Personal Website", "Development", "Hugo",  "PaperMod", "Programming", "Computer Science"]
  author: Vighnesh Shenoy
  DateFormat: "Jan 2, 2006"
  defaultTheme: dark
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
    disableHLJS: false
    disableFingerPrinting: false
    
  label:
    text: "/home/v-shenoy/"

  profileMode:
    enabled: true
    title: "Vighnesh Shenoy"
    subtitle: "Software Engineer @ Microsoft | Programming, Computer Science, Chess, Cubing and some other interesting stuff"
    imageUrl: "/DP-Rock.jpg"
    imageTitle: "a-picture-of-my-face" 
    imageWidth: 375
    imageHeight: 375

  socialIcons:
    - name: github
      url: "https://github.com/v-shenoy"
    - name: email
      url: "mailto:vighneshq@gmail.com"
    - name: cv
      url: "/resume/"
    - name: linkedin
      url: "https://www.linkedin.com/in/v-shenoy"
    - name: twitter
      url: "https://twitter.com/bitsinadatabase"
    - name: lichess
      url: "https://lichess.org/@/bitsinadatabase"
    - name: rss
      url: "/index.xml"

  editPost:
    URL: "https://github.com/v-shenoy/personal-website-dev/blob/main/content"
    Text: "Suggest changes."
    appendFilePath: true

menu:
  main:
    - identifier: posts
      name: Blog
      url: /blog/
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - identifier: search
      name: Search
      url: /search
      weight: 4
    - identifier: rss
      name: RSS
      url: /index.xml
      weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON
